package at.fhv.sysarch.lab3.actors;

public enum Actor implements IActor{
    MEDIA_STATION, BLINDS, WEATHER_SENSOR, TEMPERATURE_SENSOR, AC, FRIDGE, WEATHER_SIMULATOR,
    TEMPERATURE_SIMULATOR, ORDER_PROCESSOR
}
